version: "3.3"
services:
    caddy:
        container_name: caddy-server
        image: caddy:2.0.0-alpine
        restart: always
        ports:
            - 80:80
            - 443:443
        volumes: 
            - ./static:/usr/share/caddy
            - ./Caddyfile:/etc/caddy/Caddyfile
            - ./caddy_data:/data
    watchtower:
        container_name: watchtower
        image: v2tec/watchtower
        restart: always
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
            - /home/ubuntu/.docker/config.json:/config.json
        command: watchtower crime-dashboard essential-workers data-commons --interval 120
    crime-dashboard:
        container_name: crime-dashboard
        image: bransonf/stlcrime:latest
        restart: always
        ports:
            - 3838:3838
        depends_on: 
            - caddy
    essential-workers:
        container_name: essential-workers
        image: docker.pkg.github.com/stlrda/essential-workers/essential-workers:latest
        restart: always
        depends_on:
            - caddy
    data-commons:
        container_name: data-commons
        image: docker.pkg.github.com/stlrda/open-data-commons/crime:latest
        restart: always
        depends_on:
            - caddy
